export const initShopsBanner = [
{
        "title":"Comfortable Original Cotton Sneaker",
        "subtitle":"SPECIAL OFFER",
        "buttonName":"Shop Now",
        "description":"Handcrafted from genuine Italian leather. One inner compartment with black satin lining",
        "image":"http://localhost:3000/assets/images/products/shoes-1.png",
        "url":"http://localhost:3000/bepetshop",
        "status":1,
        "sort":1,
        "clicked":0,
        "type":"banner_home",
        "store_id":1,
    },
    {
        "title":"Minimalist Genuine Cotton Jacket",
        "subtitle":"JACKETS",
        "buttonName":"Shop Now",
        "description":"Handcrafted from genuine Italian leather. One inner compartment with black satin lining",
        "image":"http://localhost:3000/assets/images/products/jacket.png",
        "url":"http://localhost:3000/bepetshop",
        "status":1,
        "sort":1,
        "clicked":0,
        "type":"banner_home",
        "store_id":1,
    },
    {
        "title":"Stylish Genuine Comfy T-shirts",
        "subtitle":"MENS SHIRTS",
        "buttonName":"Shop Now",
        "description":"Handcrafted from genuine Italian leather. One inner compartment with black satin lining",
        "image":"http://localhost:3000/assets/images/products/t-shirt2.png",
        "url":"http://localhost:3000/bepetshop",
        "status":1,
        "sort":1,
        "clicked":0,
        "type":"banner_home",
        "store_id":1,
    }
];
