export const initShops = [
    {
        "id": 1,
        "logo":"/assets/images/shops/final_bepetshop.png",
        "template":"Fashion Shop 1",
        "phone":"0922595351",
        "email":"haongolog@gmail.com",
        "domain":"bepetshop",
        "partner":1,
        "code":"root",
        "language":"vi",
        "timezone":"Asia/Ho_Chi_Minh",
        "currency":"VND",
        "status":1,
        "active":1,
        "short_name":"BPShop",
        "favicon":"/assets/images/shops/icons/bbsfavicon.png",
    },
    {
        "id": 2,
        "logo":"/assets/images/shops/final_bepetshop.png",
        "template":"Fashion Shop 2",
        "phone":"0972918122",
        "email":"localhost@gmail.com",
        "domain":"localhost",
        "partner":1,
        "code":"root",
        "language":"en",
        "timezone":"Asia/Ho_Chi_Minh",
        "currency":"USD",
        "status":1,
        "active":1,
        "short_name":"TTPer",
        "favicon":"api/system/getFile?disk=local&path=BPShop%2Fstore%2Ffavicon_bepetshop.png",
    },
    {
        "id": 3,
        "logo":"/assets/images/shops/final_bepetshop.png",
        "template":"Fashion Shop 3",
        "phone":"0345486224",
        "email":"tutran@gmail.com",
        "domain":"ttperfume",
        "partner":1,
        "code":"root",
        "language":"en",
        "timezone":"Asia/Ho_Chi_Minh",
        "currency":"USD",
        "status":1,
        "active":1,
        "short_name":"Local",
        "favicon":"api/system/getFile?disk=local&path=BPShop%2Fstore%2Ffavicon_bepetshop.png",
    }
];
